# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import context_pb2 as context__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in context_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ContextEngineStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddItem = channel.unary_unary(
                '/mirrorneuron.context.v1.ContextEngine/AddItem',
                request_serializer=context__pb2.AddItemRequest.SerializeToString,
                response_deserializer=context__pb2.AddItemResponse.FromString,
                _registered_method=True)
        self.UpdateItem = channel.unary_unary(
                '/mirrorneuron.context.v1.ContextEngine/UpdateItem',
                request_serializer=context__pb2.UpdateItemRequest.SerializeToString,
                response_deserializer=context__pb2.UpdateItemResponse.FromString,
                _registered_method=True)
        self.GetItem = channel.unary_unary(
                '/mirrorneuron.context.v1.ContextEngine/GetItem',
                request_serializer=context__pb2.GetItemRequest.SerializeToString,
                response_deserializer=context__pb2.GetItemResponse.FromString,
                _registered_method=True)
        self.QueryItems = channel.unary_unary(
                '/mirrorneuron.context.v1.ContextEngine/QueryItems',
                request_serializer=context__pb2.QueryItemsRequest.SerializeToString,
                response_deserializer=context__pb2.QueryItemsResponse.FromString,
                _registered_method=True)
        self.LinkItems = channel.unary_unary(
                '/mirrorneuron.context.v1.ContextEngine/LinkItems',
                request_serializer=context__pb2.LinkItemsRequest.SerializeToString,
                response_deserializer=context__pb2.LinkItemsResponse.FromString,
                _registered_method=True)
        self.InvalidateItem = channel.unary_unary(
                '/mirrorneuron.context.v1.ContextEngine/InvalidateItem',
                request_serializer=context__pb2.InvalidateItemRequest.SerializeToString,
                response_deserializer=context__pb2.InvalidateItemResponse.FromString,
                _registered_method=True)
        self.GetContext = channel.unary_unary(
                '/mirrorneuron.context.v1.ContextEngine/GetContext',
                request_serializer=context__pb2.GetContextRequest.SerializeToString,
                response_deserializer=context__pb2.GetContextResponse.FromString,
                _registered_method=True)
        self.CompileContext = channel.unary_unary(
                '/mirrorneuron.context.v1.ContextEngine/CompileContext',
                request_serializer=context__pb2.CompileContextRequest.SerializeToString,
                response_deserializer=context__pb2.CompileContextResponse.FromString,
                _registered_method=True)
        self.Snapshot = channel.unary_unary(
                '/mirrorneuron.context.v1.ContextEngine/Snapshot',
                request_serializer=context__pb2.SnapshotRequest.SerializeToString,
                response_deserializer=context__pb2.SnapshotResponse.FromString,
                _registered_method=True)
        self.Restore = channel.unary_unary(
                '/mirrorneuron.context.v1.ContextEngine/Restore',
                request_serializer=context__pb2.RestoreRequest.SerializeToString,
                response_deserializer=context__pb2.RestoreResponse.FromString,
                _registered_method=True)


class ContextEngineServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')
    def UpdateItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')
    def GetItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')
    def QueryItems(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')
    def LinkItems(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')
    def InvalidateItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')
    def GetContext(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')
    def CompileContext(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')
    def Snapshot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')
    def Restore(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ContextEngineServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddItem': grpc.unary_unary_rpc_method_handler(
                    servicer.AddItem,
                    request_deserializer=context__pb2.AddItemRequest.FromString,
                    response_serializer=context__pb2.AddItemResponse.SerializeToString,
            ),
            'UpdateItem': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateItem,
                    request_deserializer=context__pb2.UpdateItemRequest.FromString,
                    response_serializer=context__pb2.UpdateItemResponse.SerializeToString,
            ),
            'GetItem': grpc.unary_unary_rpc_method_handler(
                    servicer.GetItem,
                    request_deserializer=context__pb2.GetItemRequest.FromString,
                    response_serializer=context__pb2.GetItemResponse.SerializeToString,
            ),
            'QueryItems': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryItems,
                    request_deserializer=context__pb2.QueryItemsRequest.FromString,
                    response_serializer=context__pb2.QueryItemsResponse.SerializeToString,
            ),
            'LinkItems': grpc.unary_unary_rpc_method_handler(
                    servicer.LinkItems,
                    request_deserializer=context__pb2.LinkItemsRequest.FromString,
                    response_serializer=context__pb2.LinkItemsResponse.SerializeToString,
            ),
            'InvalidateItem': grpc.unary_unary_rpc_method_handler(
                    servicer.InvalidateItem,
                    request_deserializer=context__pb2.InvalidateItemRequest.FromString,
                    response_serializer=context__pb2.InvalidateItemResponse.SerializeToString,
            ),
            'GetContext': grpc.unary_unary_rpc_method_handler(
                    servicer.GetContext,
                    request_deserializer=context__pb2.GetContextRequest.FromString,
                    response_serializer=context__pb2.GetContextResponse.SerializeToString,
            ),
            'CompileContext': grpc.unary_unary_rpc_method_handler(
                    servicer.CompileContext,
                    request_deserializer=context__pb2.CompileContextRequest.FromString,
                    response_serializer=context__pb2.CompileContextResponse.SerializeToString,
            ),
            'Snapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.Snapshot,
                    request_deserializer=context__pb2.SnapshotRequest.FromString,
                    response_serializer=context__pb2.SnapshotResponse.SerializeToString,
            ),
            'Restore': grpc.unary_unary_rpc_method_handler(
                    servicer.Restore,
                    request_deserializer=context__pb2.RestoreRequest.FromString,
                    response_serializer=context__pb2.RestoreResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mirrorneuron.context.v1.ContextEngine', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('mirrorneuron.context.v1.ContextEngine', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ContextEngine(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mirrorneuron.context.v1.ContextEngine/AddItem',
            context__pb2.AddItemRequest.SerializeToString,
            context__pb2.AddItemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
    @staticmethod
    def UpdateItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mirrorneuron.context.v1.ContextEngine/UpdateItem',
            context__pb2.UpdateItemRequest.SerializeToString,
            context__pb2.UpdateItemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
    @staticmethod
    def GetItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mirrorneuron.context.v1.ContextEngine/GetItem',
            context__pb2.GetItemRequest.SerializeToString,
            context__pb2.GetItemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
    @staticmethod
    def QueryItems(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mirrorneuron.context.v1.ContextEngine/QueryItems',
            context__pb2.QueryItemsRequest.SerializeToString,
            context__pb2.QueryItemsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
    @staticmethod
    def LinkItems(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mirrorneuron.context.v1.ContextEngine/LinkItems',
            context__pb2.LinkItemsRequest.SerializeToString,
            context__pb2.LinkItemsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
    @staticmethod
    def InvalidateItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mirrorneuron.context.v1.ContextEngine/InvalidateItem',
            context__pb2.InvalidateItemRequest.SerializeToString,
            context__pb2.InvalidateItemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
    @staticmethod
    def GetContext(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mirrorneuron.context.v1.ContextEngine/GetContext',
            context__pb2.GetContextRequest.SerializeToString,
            context__pb2.GetContextResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
    @staticmethod
    def CompileContext(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mirrorneuron.context.v1.ContextEngine/CompileContext',
            context__pb2.CompileContextRequest.SerializeToString,
            context__pb2.CompileContextResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
    @staticmethod
    def Snapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mirrorneuron.context.v1.ContextEngine/Snapshot',
            context__pb2.SnapshotRequest.SerializeToString,
            context__pb2.SnapshotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
    @staticmethod
    def Restore(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mirrorneuron.context.v1.ContextEngine/Restore',
            context__pb2.RestoreRequest.SerializeToString,
            context__pb2.RestoreResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
